'use strict'

// General
export const UNLOAD_PAGE = 'UNLOAD_PAGE'
export const LOAD_PAGE = 'LOAD_PAGE'

// Document
export const UPDATE_TEXT = 'UPDATE_TEXT'
export const BANNER_SHOW_FULL = 'BANNER_SHOW_FULL'
export const BANNER_SHOW_SHORT = 'BANNER_SHOW_SHORT'
export const BANNER_SHOW_HIDDEN = 'BANNER_SHOW_HIDDEN'
export const POPUP_HIDE_ALL = 'POPUP_HIDE_ALL'
export const POPUP_RESET = 'POPUP_RESET'
export const REQUEST_FORMATTING = 'REQUEST_FORMATTING'
export const RESET_FORMATTING = 'RESET_FORMATTING'
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT'
export const EXPANDED_VIEW = 'EXPANDED_VIEW'
export const FETCH_POST_FROM_HASH = 'FETCH_POST_FROM_HASH'